// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/search-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
var SHOPIFY_URL = "https://swifliving-showroom-build-xw1vp.myshopify.com/api/2025-07/graphql.json";
var SHOPIFY_TOKEN = "73f85d3bdb6f0f9ac02b43a88c6edf8d";
var QUERY = (
  /* GraphQL */
  `
  query Search($query: String!, $first: Int!) {
    products(first: $first, query: $query) {
      edges {
        node {
          handle
          title
          description
          availableForSale
          priceRange { minVariantPrice { amount currencyCode } }
          featuredImage { url altText }
          onlineStoreUrl
        }
      }
    }
  }
`
);
var search_products_default = defineTool({
  name: "search_products",
  title: "Search products",
  description: "Search the Furniture100 catalogue by keyword and return matching products with price, availability and product URL.",
  inputSchema: {
    query: z.string().min(1).describe("Search query, e.g. 'oak dining table'."),
    limit: z.number().int().min(1).max(20).optional().describe("Max results (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const res = await fetch(SHOPIFY_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "X-Shopify-Storefront-Access-Token": SHOPIFY_TOKEN
      },
      body: JSON.stringify({ query: QUERY, variables: { query, first: limit ?? 10 } })
    });
    if (!res.ok) {
      return { content: [{ type: "text", text: `Shopify error: ${res.status}` }], isError: true };
    }
    const json = await res.json();
    const products = (json?.data?.products?.edges ?? []).map((e) => ({
      handle: e.node.handle,
      title: e.node.title,
      description: e.node.description?.slice(0, 300),
      price: `${e.node.priceRange?.minVariantPrice?.amount} ${e.node.priceRange?.minVariantPrice?.currencyCode}`,
      inStock: e.node.availableForSale,
      image: e.node.featuredImage?.url,
      url: `https://furniture100.co.uk/product/${e.node.handle}`
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(products, null, 2) }],
      structuredContent: { products }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
var SHOPIFY_URL2 = "https://swifliving-showroom-build-xw1vp.myshopify.com/api/2025-07/graphql.json";
var SHOPIFY_TOKEN2 = "73f85d3bdb6f0f9ac02b43a88c6edf8d";
var QUERY2 = (
  /* GraphQL */
  `
  query Product($handle: String!) {
    product(handle: $handle) {
      handle
      title
      descriptionHtml
      availableForSale
      priceRange { minVariantPrice { amount currencyCode } }
      images(first: 5) { edges { node { url altText } } }
      variants(first: 20) {
        edges {
          node {
            id
            title
            availableForSale
            price { amount currencyCode }
          }
        }
      }
    }
  }
`
);
var get_product_default = defineTool2({
  name: "get_product",
  title: "Get product details",
  description: "Fetch full details for a Furniture100 product by its handle (URL slug).",
  inputSchema: {
    handle: z2.string().min(1).describe("Product handle, e.g. 'oak-dining-table'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ handle }) => {
    const res = await fetch(SHOPIFY_URL2, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "X-Shopify-Storefront-Access-Token": SHOPIFY_TOKEN2
      },
      body: JSON.stringify({ query: QUERY2, variables: { handle } })
    });
    if (!res.ok) {
      return { content: [{ type: "text", text: `Shopify error: ${res.status}` }], isError: true };
    }
    const json = await res.json();
    const p = json?.data?.product;
    if (!p) {
      return { content: [{ type: "text", text: "Product not found" }], isError: true };
    }
    const product = {
      handle: p.handle,
      title: p.title,
      description: p.descriptionHtml?.replace(/<[^>]+>/g, "").slice(0, 1e3),
      inStock: p.availableForSale,
      price: `${p.priceRange?.minVariantPrice?.amount} ${p.priceRange?.minVariantPrice?.currencyCode}`,
      images: (p.images?.edges ?? []).map((e) => e.node.url),
      variants: (p.variants?.edges ?? []).map((e) => ({
        id: e.node.id,
        title: e.node.title,
        inStock: e.node.availableForSale,
        price: `${e.node.price?.amount} ${e.node.price?.currencyCode}`
      })),
      url: `https://furniture100.co.uk/product/${p.handle}`
    };
    return {
      content: [{ type: "text", text: JSON.stringify(product, null, 2) }],
      structuredContent: { product }
    };
  }
});

// src/lib/mcp/tools/list-my-offers.ts
import { createClient } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_offers_default = defineTool3({
  name: "list_my_offers",
  title: "List my offers",
  description: "List the signed-in customer's price offers on Furniture100 products, including status (pending, accepted, countered, declined).",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).optional().describe("Max offers to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const email = ctx.getUserEmail();
    if (!email) {
      return { content: [{ type: "text", text: "No email on this account" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("offers").select("id, product_title, product_handle, offer_amount, original_price, counter_amount, status, quantity, created_at, shopify_invoice_url").eq("buyer_email", email).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { offers: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-wishlist.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_wishlist_default = defineTool4({
  name: "list_my_wishlist",
  title: "List my wishlist",
  description: "List products the signed-in customer has saved to their Furniture100 wishlist.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("wishlists").select("product_handle, product_title, product_price, product_image, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const items = (data ?? []).map((r) => ({
      ...r,
      url: `https://furniture100.co.uk/product/${r.product_handle}`
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { wishlist: items }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "fskxyiwpzvhhnezofyuc";
var mcp_default = defineMcp({
  name: "furniture100-mcp",
  title: "Furniture100",
  version: "0.1.0",
  instructions: "Furniture100 storefront tools. Use `search_products` and `get_product` to browse the catalogue. Use `list_my_offers` and `list_my_wishlist` to read the signed-in customer's saved items and price offers.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_products_default, get_product_default, list_my_offers_default, list_my_wishlist_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
