insert into public.product_reviews
  (id, product_handle, rating, title, body, author_name, source, variant_label, verified, incentivised, country, helpful_up, reviewed_at, status, admin_notes)
values
  ('3d1ff401-3d36-46cc-aa62-5029af65ece9', 'marlow-set-of-2-brown-leather-look-quilted-dining-chairs', 5,
   'Perfect',
   'Pretty Perfect

I am chuffed to bits with these gorgeous chairs. Bought based on the excellent reviews and they were not wrong. Excellent quality, fab size, quality faux leather material (no smell at all). Very comfortable and supportive and very simple and straightforward to assemble.

They have replaced my high-backed dark brown chairs which made the space look to formal. Kitchen diner now has a much more relaxed vibe.

Next day delivery, which was excellent and communication from the seller was first class. Excellent value for money. Would definitely recommend.',
   'Queen B', 'amazon', null, true, false, 'GB', 4, '2026-04-01', 'approved',
   'Amazon UK review, verified purchase, Colour Name: Brown, Set of 2. Imported 7 Sep 2026.'),
  ('c97ff05d-03f1-4779-87ee-94594cba27e3', 'marlow-set-of-2-brown-leather-look-quilted-dining-chairs', 5,
   'Great dining chairs',
   'These are fab dining chairs for the price. So easy to assemble. Look great!',
   'Anonymous', 'amazon', null, true, false, 'GB', 3, '2026-05-06', 'approved',
   'Amazon UK review, verified purchase, Colour Name: Brown, Set of 6. Posted as "Kindle Customer". Imported 7 Sep 2026.'),
  ('21992939-29ff-441b-b6cf-fa677e93bb32', 'marlow-set-of-2-grey-leather-look-quilted-dining-chairs-with-black-metal-legs', 5,
   'Great comfortable chairs',
   'Wow ! What a great buy outstanding quality and they look amazing. The chairs arrived well on time and well packaged. Easy to assemble with loads of spare screws you can put a chair together in 10 minutes. I would give this product 100% for looks style and comfort yes it was a great buy.',
   'Angus Burt', 'amazon', null, true, false, 'GB', 1, '2026-01-30', 'approved',
   'Amazon UK review, verified purchase, Colour Name: Grey, Set of 6. Imported 7 Sep 2026.'),
  ('d23a444f-6fd7-4018-af6d-32b14b683ffc', 'marlow-set-of-2-brown-leather-look-quilted-dining-chairs', 5,
   '6 dinning chairs',
   'Really happy with these chairs, they look good and comfortable, great price.',
   'Diane M.', 'amazon', null, true, false, 'GB', 0, '2026-06-09', 'approved',
   'Amazon UK review, verified purchase, no colour recorded. Imported 7 Sep 2026.'),
  ('fb7a5b14-eda7-42de-a502-163b4bf80aad', 'marlow-set-of-2-brown-leather-look-quilted-dining-chairs', 5,
   'Brilliant chairs, so comfy and stylish too',
   'I ordered 4 x chairs to go with our dining table. They arrived next day by DPD, the chairs were really well packed and only took 5 mins to put together. Spare bolts too, which is brilliant. Thanks, they look amazing - photo to follow 👍🏼',
   'Joanna Williams-Clarke', 'amazon', null, true, false, 'GB', 4, '2026-05-14', 'approved',
   'Amazon UK review, verified purchase, no colour recorded. Imported 7 Sep 2026.'),
  ('eb25e349-989e-4e67-a8a9-c61262570bd7', 'marlow-set-of-2-grey-leather-look-quilted-dining-chairs-with-black-metal-legs', 5,
   'Beautiful chairs',
   'Beautiful chairs, nice design look very expensive. Really easy to put together. Padding is nice and soft. Very nice chairs. Only down side is very light but still absolutely fine!',
   'Leigh', 'amazon', 'Dark Grey', true, false, 'GB', 0, '2026-04-08', 'approved',
   'Amazon UK review, verified purchase, Colour Name: Dark Grey, Set of 4. Dark Grey is not a colourway we sell. Imported 7 Sep 2026.'),
  ('ff7f07e5-bbd8-4219-8947-4456f9a1667e', 'marlow-set-of-2-grey-leather-look-quilted-dining-chairs-with-black-metal-legs', 5,
   'Good product',
   'Good quality chairs at a great price',
   'Anonymous', 'amazon', null, true, false, 'GB', 0, '2026-07-13', 'approved',
   'Amazon UK review, verified purchase, Colour Name: Grey, Set of 4. Posted as "Amazon Customer". Imported 7 Sep 2026.'),
  ('8ce58a0b-9f7a-4205-aa3d-bb7c0e3ce7b6', 'marlow-set-of-2-brown-leather-look-quilted-dining-chairs', 5,
   'Great chairs',
   'Easy to assemble and look great',
   'Mark', 'amazon', null, true, false, 'GB', 1, '2026-05-30', 'approved',
   'Amazon UK review, verified purchase, no colour recorded. Imported 7 Sep 2026.'),
  ('8a5c0a08-c3bb-44d6-8275-43c322fe0973', 'marlow-set-of-2-brown-leather-look-quilted-dining-chairs', 5,
   'Chairs',
   'Very nice chairs , delivered in 2 packages over 2 days but very prompt',
   'Helen', 'amazon', null, true, false, 'GB', 0, '2026-09-02', 'approved',
   'Amazon UK review, verified purchase, no colour recorded. Imported 7 Sep 2026.'),
  ('80411ac6-b8dc-4170-8935-d8c5dc8b03ed', 'marlow-set-of-2-grey-leather-look-quilted-dining-chairs-with-black-metal-legs', 5,
   'Gorgeous sturdy chair',
   'Absolutely gorgeous!

Looks more expensive than what it was.

Comfy and stylish.

Really pleased!',
   'Ri20', 'amazon', null, true, false, 'GB', 0, '2026-08-25', 'approved',
   'Amazon UK review, verified purchase, Colour Name: Grey, Set of 1. Imported 7 Sep 2026.'),
  ('dcc98c94-cafc-4517-8848-bdf27e653021', 'marlow-set-of-2-brown-leather-look-quilted-dining-chairs', 5,
   'Look very expensive',
   'Very stylish and comfortable',
   'tb', 'amazon', null, true, false, 'GB', 0, '2026-08-20', 'approved',
   'Amazon UK review, verified purchase, Colour Name: Brown, Set of 2. Imported 7 Sep 2026.'),
  ('d9d5f1da-8517-44c8-875e-2f9d574514ff', 'marlow-set-of-2-brown-leather-look-quilted-dining-chairs', 5,
   'They look classy',
   'These chairs are absolutely beautiful had so many compliments',
   'Shani sheppard', 'amazon', null, true, false, 'GB', 0, '2026-08-25', 'approved',
   'Amazon UK review, verified purchase, no colour recorded. Came with a video, which we do not carry. Imported 7 Sep 2026.'),
  ('50b5b849-2e95-4fde-a926-0915daad02de', 'marlow-set-of-2-grey-leather-look-quilted-dining-chairs-with-black-metal-legs', 5,
   'Chairs',
   'Love them easy to wipe look stylish',
   'Anonymous', 'amazon', null, true, false, 'GB', 0, '2026-08-02', 'approved',
   'Amazon UK review, verified purchase, Colour Name: Grey, Set of 6. Posted as "Amazon Customer". Imported 7 Sep 2026.'),
  ('c8e2f794-1907-47cf-ab4f-9c10e8f683f3', 'marlow-set-of-2-dark-brown-leather-look-quilted-dining-chairs', 5,
   'Comfort',
   'Excellent chairs

Really comfortable',
   'ryan', 'amazon', null, true, false, 'GB', 0, '2026-07-30', 'approved',
   'Amazon UK review, verified purchase, Colour Name: Dark Brown, Set of 2. Imported 7 Sep 2026.'),
  ('80e21699-7430-4322-9143-2583bd509d6e', 'marlow-set-of-2-brown-leather-look-quilted-dining-chairs', 5,
   'Great quality',
   'Great quality',
   'Daniel', 'amazon', null, true, false, 'GB', 0, '2026-07-24', 'approved',
   'Amazon UK review, verified purchase, Colour Name: Brown, Set of 2. Imported 7 Sep 2026.'),
  ('6e1e5234-626c-4eca-a994-07d972c47f42', 'marlow-set-of-2-brown-leather-look-quilted-dining-chairs', 5,
   'Chairs',
   'Chairs are a lovely color very old school but look amazing in my kitchen nice and wipeable good sturdy legs too got the ottoman in same color',
   'Boothy', 'amazon', null, true, false, 'GB', 0, '2026-06-22', 'approved',
   'Amazon UK review, verified purchase, Colour Name: Brown, Set of 2. Imported 7 Sep 2026.'),
  ('247ee1db-3837-43b1-9589-e21e4eaf2c4c', 'marlow-set-of-2-grey-leather-look-quilted-dining-chairs-with-black-metal-legs', 5,
   'Great',
   'Well made ,sturdy and light weight, we are very pleased with this purchase.',
   'Old man', 'amazon', 'Dark Grey', true, false, 'GB', 0, '2026-06-17', 'approved',
   'Amazon UK review, verified purchase, Colour Name: Dark Grey, Set of 4. Dark Grey is not a colourway we sell. Imported 7 Sep 2026.'),
  ('33055ee2-690b-401a-95a3-543a1466378f', 'marlow-set-of-2-brown-leather-look-quilted-dining-chairs', 5,
   null,
   'Love these chairs, exactly as described.

Very high quality for the money I would definitely recommend.',
   'Claire', 'amazon', null, true, false, 'GB', 0, '2026-06-09', 'approved',
   'Amazon UK review, verified purchase, Colour Name: Brown, Set of 4. Amazon title was "Woltu Chairs", the supplier''s brand rather than a title, so no title is shown. Body untouched. Imported 7 Sep 2026.'),
  ('afc34dc5-ddda-44d1-89c8-1fc65a3c6cce', 'marlow-set-of-2-grey-leather-look-quilted-dining-chairs-with-black-metal-legs', 5,
   'Softness',
   'Really comfortable chairs',
   'Anonymous', 'amazon', 'Dark Grey', true, false, 'GB', 0, '2026-06-20', 'approved',
   'Amazon UK review, verified purchase, Colour Name: Dark Grey, Set of 4. Posted as "Amazon Customer". Dark Grey is not a colourway we sell. Imported 7 Sep 2026.'),
  ('10e1d3e9-d061-45ab-ab9c-404e467d3e49', 'marlow-set-of-2-brown-leather-look-quilted-dining-chairs', 5,
   'Chairs for Games Night and Beyond',
   'Sometimes, one just needs a dining table and 6 chairs urgently for games night. These WOLTU chairs popped up in my search results and lo and behold, 2 days later they are assembled and beautiful in our home!

The delivery was swift and a smooth. The communication with the seller was excellent. The product was easy to assemble, it’s sturdy and stable and fits perfectly with the dining table we ordered separately. The PU leather cover is soft and looks great.',
   'Imre Pesta', 'amazon', null, true, false, 'GB', 0, '2026-03-06', 'approved',
   'Amazon UK review, verified purchase, no colour recorded. Names the supplier brand in the body; kept verbatim, flagged for the owner. Imported 7 Sep 2026.'),
  ('cbb1ee23-5826-4ad2-bda6-5def3c127c6d', 'marlow-set-of-2-brown-leather-look-quilted-dining-chairs', 5,
   'Big bums won''t fit',
   'Great chairs! Looking good and comfortable, but not for bigger people 😁',
   'egija grintale', 'amazon', null, true, false, 'GB', 2, '2026-06-08', 'approved',
   'Amazon UK review, verified purchase, Colour Name: Brown, Set of 4. Imported 7 Sep 2026.'),
  ('4c94fc46-82de-4864-85a8-eb8fadf6f2a3', 'marlow-set-of-2-grey-leather-look-quilted-dining-chairs-with-black-metal-legs', 5,
   'Great looking chairs',
   'Delighted with these chairs would recommend',
   'Ann McGuire', 'amazon', null, true, false, 'GB', 0, '2026-06-10', 'approved',
   'Amazon UK review, verified purchase, Colour Name: Grey, Set of 6. Imported 7 Sep 2026.'),
  ('0a255f25-875c-4a8e-b321-c0cffc37e22f', 'marlow-set-of-2-brown-leather-look-quilted-dining-chairs', 5,
   'Good quality',
   'Woltu 6 dining chairs is very good. Have been using it for over 2 yrs now... still strong!',
   'GRACE BAILEY', 'amazon', null, true, false, 'GB', 0, '2026-05-18', 'approved',
   'Amazon UK review, verified purchase, no colour recorded. Names the supplier brand in the body; kept verbatim, flagged for the owner. Imported 7 Sep 2026.'),
  ('95b71f90-7d55-45e4-87a3-031584dc744d', 'marlow-set-of-2-brown-leather-look-quilted-dining-chairs', 5,
   'More 2 chairs',
   'I loved the chairs',
   'Rita S.', 'amazon', null, true, false, 'GB', 0, '2026-06-06', 'approved',
   'Amazon UK review, verified purchase, Colour Name: Brown, Set of 6. Imported 7 Sep 2026.'),
  ('35c9766e-8e24-4e6d-a456-3f6841dea220', 'marlow-set-of-2-brown-leather-look-quilted-dining-chairs', 5,
   'chairs',
   'easy to assemble lovely colour arrived well protected great price x',
   'Michele gilbert', 'amazon', null, true, false, 'GB', 0, '2026-05-04', 'approved',
   'Amazon UK review, verified purchase, no colour recorded. Imported 7 Sep 2026.'),
  ('09b853f8-a35b-47c7-a599-4eb8af4552db', 'marlow-set-of-2-grey-leather-look-quilted-dining-chairs-with-black-metal-legs', 5,
   'Lovely chairs',
   'Lovely chairs. Super comfy and great quality for the price. Look and feel much more expensive. Very happy.',
   'Sharon Miller', 'amazon', null, true, false, 'GB', 0, '2026-04-20', 'approved',
   'Amazon UK review, verified purchase, Colour Name: Grey, Set of 6. Imported 7 Sep 2026.'),
  ('1db80d1b-3114-4c83-9716-e9a69504fad0', 'marlow-set-of-2-brown-leather-look-quilted-dining-chairs', 5,
   'Great looking, comfy chairs',
   'Lovely chairs, very comfortable and sturdy. Was affraid the will be small but they are not. Plenty of comfy sitting space👌visual as per pictures, would buy again.',
   'Sylvia', 'amazon', null, true, false, 'GB', 1, '2026-03-18', 'approved',
   'Amazon UK review, verified purchase, Colour Name: Brown, Set of 4. Imported 7 Sep 2026.'),
  ('2dbf799e-81dd-455f-a13f-9954e8906746', 'marlow-set-of-2-brown-leather-look-quilted-dining-chairs', 5,
   'Nice chairs',
   'Nice looking sturdy chairs . Value for money',
   'Mrs AV Dickinson', 'amazon', null, true, false, 'GB', 0, '2026-04-12', 'approved',
   'Amazon UK review, verified purchase, Colour Name: Brown, Set of 2. Imported 7 Sep 2026.'),
  ('f3251f18-637e-4d5f-97fd-a717c13899f5', 'marlow-set-of-2-grey-leather-look-quilted-dining-chairs-with-black-metal-legs', 5,
   'Comfortable dining chairs',
   'Great dining room chairs',
   'michael joyce', 'amazon', null, true, false, 'GB', 0, '2026-03-25', 'approved',
   'Amazon UK review, verified purchase, Colour Name: Grey, Set of 6. Imported 7 Sep 2026.'),
  ('ba9fd685-56ca-47ca-a2c9-6a805810053c', 'marlow-set-of-2-grey-leather-look-quilted-dining-chairs-with-black-metal-legs', 5,
   null,
   'Very comfortable. Easy to put together. Good quality. Very sturdy',
   'susan james', 'amazon', 'Dark Grey', true, false, 'GB', 0, '2026-02-04', 'approved',
   'Amazon UK review, verified purchase, Colour Name: Dark Grey, Set of 2. Amazon title was "Wolto dining chairs", the supplier''s brand rather than a title, so no title is shown. Body untouched. Dark Grey is not a colourway we sell. Imported 7 Sep 2026.')
on conflict (id) do nothing;

-- The customer photo strip, on every colour of the chair.
insert into public.product_overrides (product_handle, field_key, field_value)
select handle, 'review_photos', '["/reviews/marlow-quilted-dining-chair-review-1.webp","/reviews/marlow-quilted-dining-chair-review-2.webp","/reviews/marlow-quilted-dining-chair-review-3.webp","/reviews/marlow-quilted-dining-chair-review-4.webp","/reviews/marlow-quilted-dining-chair-review-5.webp","/reviews/marlow-quilted-dining-chair-review-6.webp","/reviews/marlow-quilted-dining-chair-review-7.webp","/reviews/marlow-quilted-dining-chair-review-8.webp","/reviews/marlow-quilted-dining-chair-review-9.webp","/reviews/marlow-quilted-dining-chair-review-10.webp","/reviews/marlow-quilted-dining-chair-review-11.webp","/reviews/marlow-quilted-dining-chair-review-12.webp","/reviews/marlow-quilted-dining-chair-review-13.webp","/reviews/marlow-quilted-dining-chair-review-14.webp"]'
from unnest(array[
  'marlow-set-of-2-brown-leather-look-quilted-dining-chairs',
  'marlow-set-of-2-dark-brown-leather-look-quilted-dining-chairs',
  'marlow-set-of-2-grey-leather-look-quilted-dining-chairs-with-black-metal-legs'
]) as handle
on conflict (product_handle, field_key) do update set field_value = excluded.field_value;