insert into public.product_reviews
  (id, product_handle, rating, title, body, author_name, source, variant_label, verified, incentivised, country, helpful_up, reviewed_at, status, admin_notes)
values
  ('cae36326-f9a1-4d73-8498-bfb3c35a7b19', 'dusks-set-of-2-black-dining-chairs', 5,
   'Look nice and comfortable , easy to assemble',
   'Easy to assemble, quite sturdy , the arms r low so no scratches to faux leather rubbing against the table, good quality, look very nice , cushioning is ok but a bit more amount can be added to make it more durable .',
   'Shanza', 'amazon', null, true, false, 'GB', 0, '2026-02-07', 'approved',
   'Amazon UK review, verified purchase, Colour Name: Black, 2er Set. Five stars but notes the cushioning could be deeper. Imported 7 Sep 2026.'),
  ('27f3be23-037a-470b-962f-bc5d2bf06d58', 'dusks-set-of-2-brown-dining-chairs', 5,
   'Dining chairs set of 4',
   'Just what we wanted, very happy with price, they look great and great quality',
   'Richard Dorricott', 'amazon', null, true, false, 'GB', 0, '2026-03-10', 'approved',
   'Amazon UK review, verified purchase, Colour Name: Brown, 4er Set. Imported 7 Sep 2026.'),
  ('a6d81103-6196-4cca-910a-feb6e97cd5cd', 'dusks-set-of-2-brown-dining-chairs', 5,
   'dining room chairs',
   'very pleased with them',
   'Mags', 'amazon', null, true, false, 'GB', 0, '2026-03-02', 'approved',
   'Amazon UK review, verified purchase, Colour Name: Brown, 4er Set. Imported 7 Sep 2026.'),
  ('3edcc587-c017-4cf0-964b-38f819031d48', 'dusks-set-of-2-black-dining-chairs', 4,
   'Superb Chairs',
   'Superb Chairs. Easy to construct with clear instruction and very solid design',
   'Adrian Lazarus Smith', 'amazon', null, true, false, 'GB', 0, '2026-04-30', 'approved',
   'Amazon UK review, verified purchase, Colour Name: Black, 2er Set. Imported 7 Sep 2026.'),
  ('5ec42cce-6102-48f8-a26e-688f650fc39c', 'dusks-set-of-2-black-dining-chairs', 5,
   'Chairs',
   'Very happy with these chairs they go really well with the table very comfortable and easy to assemble',
   'mark bryan', 'amazon', null, true, false, 'GB', 1, '2025-12-21', 'approved',
   'Amazon UK review, verified purchase, Colour Name: Black, 6er Set. Imported 7 Sep 2026.'),
  ('3b274c85-fcf4-4ba2-8535-50cda95a0911', 'dusks-set-of-2-black-dining-chairs', 5,
   'Super stylish dining chairs',
   'These chairs are so stylish, good quality for the price and unique. They were easy to assemble. They wipe clean well. I absolutely love them.',
   'Miss Stacey Wilde', 'amazon', null, true, false, 'GB', 0, '2025-04-27', 'approved',
   'Amazon UK review, verified purchase, Colour Name: Black, 2er Set. Imported 7 Sep 2026.'),
  ('111b5d16-65b6-4573-a591-4e7d1d58184f', 'dusks-set-of-2-brown-dining-chairs', 5,
   'Dining chairs',
   'Ordered 6 chairs pleased with them',
   'Mrs V Murphy', 'amazon', null, true, false, 'GB', 0, '2026-07-28', 'approved',
   'Amazon UK review, verified purchase, Colour Name: Brown, 2er Set. Imported 7 Sep 2026.'),
  ('37780759-e216-4e7d-92f2-87bdf42bb666', 'dusks-set-of-2-black-dining-chairs', 5,
   'Good quality',
   'Good quality at a very good price. Love the colour and the style.',
   'TJ65', 'amazon', null, true, false, 'GB', 0, '2025-05-19', 'approved',
   'Amazon UK review, verified purchase, Colour Name: Black, 2er Set. Imported 7 Sep 2026.'),
  ('e7cf312a-22b3-45ec-9f3f-c549fdb5e1f4', 'dusks-set-of-2-black-dining-chairs', 4,
   null,
   'Would have given 5 stars but found it hard to get stickers for the bottom of the chairs to prevent them from damaging the floor otherwise beautiful chairs',
   'Christine', 'amazon', null, true, false, 'GB', 0, '2025-12-29', 'approved',
   'Amazon UK review, verified purchase, Colour Name: Black, 4er Set. Amazon title was "Mrs", a salutation rather than a title, so no title is shown. Body untouched. Imported 7 Sep 2026.'),
  ('f7170158-5adb-419f-a2cb-e62b4ef98488', 'dusks-set-of-2-black-dining-chairs', 5,
   'Just amazing',
   'Amazing and very comfy',
   'Klaudia', 'amazon', null, true, false, 'GB', 0, '2026-03-29', 'approved',
   'Amazon UK review, verified purchase, Colour Name: Black, 2er Set. Imported 7 Sep 2026.'),
  ('a3645ddd-ce84-42c6-9cae-0528919dfbf3', 'dusks-set-of-2-black-dining-chairs', 5,
   'Very nice chairs.',
   'Very nice sturdy well built chairs.',
   'Peter Hailey', 'amazon', null, true, false, 'GB', 0, '2025-12-20', 'approved',
   'Amazon UK review, verified purchase, Colour Name: Black, 4er Set. Imported 7 Sep 2026.'),
  ('de27efe5-c2a1-4818-9463-fb63c751e528', 'dusks-set-of-2-black-dining-chairs', 5,
   null,
   'Ok',
   'Piotr Zajaczkowski', 'amazon', null, true, false, 'GB', 0, '2025-12-09', 'approved',
   'Amazon UK review, verified purchase, Colour Name: Black, 2er Set. Amazon title was "Pz", the reviewer''s initials, so no title is shown. Imported 7 Sep 2026.'),
  ('45dbc049-c996-4412-878a-f31bc063f703', 'dusks-set-of-2-black-dining-chairs', 5,
   'Lovely Chairs',
   'These chairs are well made and so simple to build as they only need the legs attached

Well pleased with them .well packaged and very fast delivery .

Would definitely recommend',
   'Agnes', 'amazon', null, true, false, 'GB', 0, '2025-05-04', 'approved',
   'Amazon UK review, verified purchase, Colour Name: Black, 2er Set. Imported 7 Sep 2026.'),
  ('c266c599-1d5d-44b1-956e-611d3722338c', 'dusks-set-of-2-black-dining-chairs', 5,
   'Very nice',
   'Nice sturdy comfy chairs , easy to assemble',
   'Hu''son', 'amazon', null, true, false, 'GB', 0, '2025-08-23', 'approved',
   'Amazon UK review, verified purchase, Colour Name: Black, 4er Set. Imported 7 Sep 2026.'),
  ('75106a94-6bd8-4133-8a25-bf5990ce1204', 'dusks-set-of-2-brown-dining-chairs', 5,
   'Excellent value for money',
   'Arrived on time, so pleased with colour and quality. Colour match to my sofas is excellent it’s always a gamble when buying online but so very pleased I did with this product.',
   'M Marshall', 'amazon', null, true, false, 'GB', 0, '2024-12-08', 'approved',
   'Amazon UK review, verified purchase, Colour Name: Brown, 6er Set. Imported 7 Sep 2026.'),
  ('bd3e656e-ecf0-4a17-9af0-ddf14737c1aa', 'dusks-set-of-2-black-dining-chairs', 5,
   'Very comfortable',
   'Received these beautiful black chairs earlier than expected.

Very comfortable and look very glamorous around our kitchen table. Highly recommended.',
   'Mitchell', 'amazon', null, true, false, 'GB', 0, '2025-01-18', 'approved',
   'Amazon UK review, verified purchase, Colour Name: Black, 2er Set. Imported 7 Sep 2026.'),
  ('540a0003-c7b4-471d-91ec-52b5edfb341f', 'dusks-set-of-2-brown-dining-chairs', 5,
   'Very happy lovey chairs',
   'Absolutely lovely chairs I purchased 6 and for the price they are fabulous very expensive looking and easy to build and assemble with all bits you need very happy, also super speedy delivery and good communication with seller with tracking info',
   'Jemma Saunders', 'amazon', null, true, false, 'GB', 0, '2024-01-28', 'approved',
   'Amazon UK review, verified purchase, Colour Name: Brown, 6er Set. Oldest date in the set. Imported 7 Sep 2026.'),
  ('58da65f7-fcbc-48c5-89d0-44c6c617dac4', 'dusks-set-of-2-brown-dining-chairs', 5,
   'Perfect chair',
   'I recommend these chairs because they are good quality and good price. The backrest is great for the back. Perfect for everyday use.',
   'Nadia', 'amazon', null, true, false, 'GB', 1, '2024-10-21', 'approved',
   'Amazon UK review, verified purchase, Colour Name: Brown, 2er Set. Imported 7 Sep 2026.'),
  ('db516ef8-f9d7-42f2-98e8-2afd88df3bb9', 'dusks-set-of-2-black-dining-chairs', 5,
   'Value for money',
   'Excellent dining chairs. Well made and comfortable too 😌',
   'Craig Mckenzie', 'amazon', null, true, false, 'GB', 0, '2024-12-31', 'approved',
   'Amazon UK review, verified purchase, Colour Name: Black, 4er Set. Imported 7 Sep 2026.')

on conflict (id) do nothing;

insert into public.product_overrides (product_handle, field_key, field_value)
select handle, 'review_photos', '["/reviews/dusks-dining-chair-review-1.webp","/reviews/dusks-dining-chair-review-2.webp","/reviews/dusks-dining-chair-review-3.webp","/reviews/dusks-dining-chair-review-4.webp","/reviews/dusks-dining-chair-review-5.webp","/reviews/dusks-dining-chair-review-6.webp","/reviews/dusks-dining-chair-review-7.webp","/reviews/dusks-dining-chair-review-8.webp","/reviews/dusks-dining-chair-review-9.webp","/reviews/dusks-dining-chair-review-10.webp","/reviews/dusks-dining-chair-review-11.webp"]'
from unnest(array[
  'dusks-set-of-2-brown-dining-chairs',
  'dusks-set-of-2-black-dining-chairs'
]) as handle
on conflict (product_handle, field_key) do update set field_value = excluded.field_value;